name: dmsp-dispersion
channels:
  - conda-forge
dependencies:
  # Base python
  - python==3.10
  # Pip dependencies
  - pip
  - pip:
    - astropy==6.0.0
    - matplotlib==3.8.2
    - numpy==1.26.3
    - pandas==2.1.4      
    - intervaltree==3.1.0
    - progressbar2==3.53.1
    - cdflib==1.2.3
    - termcolor==1.1.0
    - madrigalWeb
    - python-dateutil
    - h5py==3.10.0
    - scipy==1.11.4
