name: dmsp-dispersion
dependencies:
  - python==3.8
  - h5py==2.10.0
  - jupyterlab==2.2.6
  - matplotlib==3.3.2
  - numpy==1.19.2
  - pandas==1.1.3
  - scikit-learn==0.23.2
  - pip
  - pip:
    - intervaltree==3.1.0
    - progressbar2==3.53.1
