name: dmsp-dispersion
dependencies:
  - python==3.8
  - astropy==4.0.2
  - h5py==2.10.0
  - jupyterlab==2.2.6
  - matplotlib==3.3.4
  - numpy==1.19.2
  - pandas==1.1.3
  - scikit-learn==0.23.2
  - pip
  - pip:
    - intervaltree==3.1.0
    - nbstripout==0.3.9
    - progressbar2==3.53.1
    - spacepy==0.2.1
    - termcolor==1.1.0
    - madrigalWeb
